version: '3.5'
services:

  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - "3030:3030"
    expose:
      - "3030"
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    # build: ./deploy/middleware
    container_name: middleware
    build:
      context: ./
      dockerfile: middleware/container/Dockerfile
    # command: sh -c "/container/docker-start-min.sh"
    command: sh -c "/container/docker-start-dev.sh"
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./middleware/container:/container
      - ./middleware/logs:/archipelago/middleware/logs
      - ./middleware/jwt:/archipelago/middleware/jwt
      - ./middleware/uploads:/archipelago/middleware/uploads
      - ./middleware:/archipelago/middleware
      - ../semapps:/semapps
    expose:
      - "3000"
    ports: 
      - 3000:3000

  frontend:
    # build: ./deploy/frontend
    build:
      context: ./
      dockerfile: deploy/frontend/Dockerfile
    container_name: frontend
    command: sh -c "/container/docker-start-dev.sh"
    volumes: 
      - ./frontend/container:/container
    restart: always
    expose:
      - "4000"
    ports:
      - 4000:4000

  redis:
    image: redis
    container_name: redis
    expose:
      - "6379"
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]
